version: "3.8"

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.dev
    env_file:
      - .env
    container_name: taxi_django_api
    command: daphne -b 0.0.0.0 -p 8000 config.asgi:application
    volumes:
      - .:/app
      - ./logs:/app/logs
    ports:
      - "8000:8000"
    environment:
      - DJANGO_SETTINGS_MODULE=config.settings.development
      - REDIS_URL=redis://redis:6379/0
      - DB_HOST=db
      - DB_NAME=$DB_NAME
      - DB_USER=$DB_USER
      - DB_PASSWORD=$DB_PASSWORD
    depends_on:
      redis:
        condition: service_healthy
      db:
        condition: service_healthy
  db:
    image: postgis/postgis:18-3.6
    container_name: taxi_db_container
    environment:
      POSTGRES_DB: $DB_NAME
      POSTGRES_USER: $DB_USER
      POSTGRES_PASSWORD: $DB_PASSWORD
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - /var/lib/postgresql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:8.4-alpine
    container_name: taxi_redis
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5

  worker:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: taxi_celery_worker
    command: celery -A config worker -l info --pool=solo
    volumes:
      - .:/app
    environment:
      - DJANGO_SETTINGS_MODULE=config.settings.development
      - REDIS_URL=redis://redis:6379/0
      - DB_HOST=db
      - DB_NAME=$DB_NAME
      - DB_USER=$DB_USER
      - DB_PASSWORD=$DB_PASSWORD
    depends_on:
      redis:
        condition: service_healthy
      db:
        condition: service_healthy

  beat:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: taxi_celery_beat
    command: celery -A config beat -l info --scheduler django_celery_beat.schedulers:DatabaseScheduler
    volumes:
      - .:/app
    environment:
      - REDIS_URL=redis://redis:6379/0
      - DB_HOST=db
    depends_on:
      - redis
      - db

  flower:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: taxi_flower
    ports:
      - "5555:5555"
    volumes:
      - .:/app
    environment:
      - DJANGO_SETTINGS_MODULE=config.settings.development
      - REDIS_URL=redis://redis:6379/0
      - DB_HOST=db
      - DB_NAME=$DB_NAME
      - DB_USER=$DB_USER
      - DB_PASSWORD=$DB_PASSWORD
    command: celery -A config flower --port=5555
    depends_on:
      - redis
      - worker
      - db

volumes:
  postgres_data: