# Generated by Django 5.1.15 on 2026-04-13 21:00

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="device",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Device",
                "verbose_name_plural": "Devices",
            },
        ),
        migrations.RemoveIndex(
            model_name="device",
            name="devices_fcm_tok_d8ae1e_idx",
        ),
        migrations.AddField(
            model_name="device",
            name="app_version",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="device",
            name="device_model",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="device",
            name="device_name",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="device",
            name="os_version",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="device",
            name="registration_id",
            field=models.TextField(blank=True, db_index=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="device",
            name="device_type",
            field=models.CharField(
                choices=[
                    ("android", "Android"),
                    ("ios", "iOS"),
                    ("web", "Web"),
                    ("expo", "Expo"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="device",
            name="fcm_token",
            field=models.TextField(blank=True, db_index=True, null=True),
        ),
        migrations.AddIndex(
            model_name="device",
            index=models.Index(
                fields=["registration_id"], name="devices_registr_7891cd_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="device",
            index=models.Index(
                fields=["device_type", "is_active"], name="devices_device__81bde7_idx"
            ),
        ),
    ]
