# Generated by Django 5.1.15 on 2026-04-05 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="date_of_birth",
            field=models.DateField(
                blank=True, help_text="User date of birth", null=True
            ),
        ),
    ]
