# Generated by Django 5.1.15 on 2026-04-13 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("users", "0002_user_date_of_birth"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="user",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Користувач",
                "verbose_name_plural": "Користувачі",
            },
        ),
        migrations.RemoveIndex(
            model_name="user",
            name="users_role_0ace22_idx",
        ),
        migrations.RemoveField(
            model_name="user",
            name="role",
        ),
        migrations.AddField(
            model_name="user",
            name="average_rating",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=3,
                verbose_name="Середній рейтинг",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="is_driver",
            field=models.BooleanField(
                default=False,
                help_text="Має доступ до driver-app",
                verbose_name="Водій",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="is_passenger",
            field=models.BooleanField(
                default=True,
                help_text="Має доступ до client-app",
                verbose_name="Пасажир",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="total_rides",
            field=models.PositiveIntegerField(default=0, verbose_name="Всього поїздок"),
        ),
        migrations.AddField(
            model_name="user",
            name="total_spent",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=12,
                verbose_name="Всього витрачено",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="clerk_user_id",
            field=models.CharField(
                blank=True,
                db_index=True,
                max_length=255,
                null=True,
                unique=True,
                verbose_name="Clerk ID",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Створено"),
        ),
        migrations.AlterField(
            model_name="user",
            name="date_of_birth",
            field=models.DateField(
                blank=True, null=True, verbose_name="Дата народження"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(
                db_index=True, max_length=254, unique=True, verbose_name="Email"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="fcm_token",
            field=models.TextField(blank=True, verbose_name="FCM Token"),
        ),
        migrations.AlterField(
            model_name="user",
            name="first_name",
            field=models.CharField(blank=True, max_length=100, verbose_name="Ім'я"),
        ),
        migrations.AlterField(
            model_name="user",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="Активний"),
        ),
        migrations.AlterField(
            model_name="user",
            name="is_staff",
            field=models.BooleanField(
                default=False,
                help_text="Доступ до admin панелі",
                verbose_name="Адміністратор",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="is_verified",
            field=models.BooleanField(default=False, verbose_name="Підтверджений"),
        ),
        migrations.AlterField(
            model_name="user",
            name="last_login",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Останній вхід"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="last_name",
            field=models.CharField(blank=True, max_length=100, verbose_name="Прізвище"),
        ),
        migrations.AlterField(
            model_name="user",
            name="phone_number",
            field=models.CharField(
                blank=True,
                max_length=20,
                null=True,
                unique=True,
                verbose_name="Телефон",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="profile_image",
            field=models.URLField(blank=True, max_length=500, verbose_name="Фото"),
        ),
        migrations.AlterField(
            model_name="user",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="Оновлено"),
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(
                fields=["is_passenger"], name="users_is_pass_265a84_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(fields=["is_driver"], name="users_is_driv_dece71_idx"),
        ),
    ]
