# Generated by Django 5.1.15 on 2026-04-13 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_alter_user_options_remove_user_users_role_0ace22_idx_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="city",
            field=models.CharField(blank=True, max_length=100, verbose_name="Місто"),
        ),
        migrations.AddField(
            model_name="user",
            name="language",
            field=models.CharField(
                choices=[
                    ("uk", "Українська"),
                    ("en", "English"),
                    ("pl", "Polski"),
                    ("de", "Deutsch"),
                    ("fr", "Français"),
                ],
                default="uk",
                max_length=5,
                verbose_name="Мова",
            ),
        ),
    ]
