# Generated by Django 5.1.15 on 2026-04-13 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_user_city_user_language"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="email_verification_token",
            field=models.CharField(
                blank=True,
                max_length=100,
                null=True,
                verbose_name="Токен верифікації email",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="email_verified",
            field=models.BooleanField(default=False, verbose_name="Email підтверджено"),
        ),
        migrations.AddField(
            model_name="user",
            name="gender",
            field=models.CharField(
                blank=True,
                choices=[
                    ("M", "Чоловік"),
                    ("F", "Жінка"),
                    ("O", "Інше"),
                    ("N", "Не вказано"),
                ],
                default="N",
                max_length=1,
                verbose_name="Стать",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="phone_verification_code",
            field=models.CharField(
                blank=True,
                max_length=6,
                null=True,
                verbose_name="Код верифікації телефону",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="phone_verification_expires",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Термін дії коду верифікації"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="phone_verified",
            field=models.BooleanField(
                default=False, verbose_name="Телефон підтверджено"
            ),
        ),
    ]
