# Generated by Django 5.1.15 on 2026-04-13 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_user_email_verification_token_user_email_verified_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="timezone",
            field=models.CharField(
                default="Europe/Kiev", max_length=50, verbose_name="Часовий пояс"
            ),
        ),
    ]
