# Generated by Django 5.1.15 on 2026-04-15 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0007_user_account_locked_until_user_backup_codes_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="profile_image",
            field=models.TextField(blank=True, verbose_name="Фото"),
        ),
    ]
