# Generated by Django 5.1.15 on 2026-03-11 12:59

import django.contrib.gis.db.models.fields
import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("drivers", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Ride",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("accepted", "Accepted"),
                            ("in_progress", "In Progress"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "vehicle_type",
                    models.CharField(
                        choices=[
                            ("economy", "Economy"),
                            ("comfort", "Comfort"),
                            ("business", "Business"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "pickup_location",
                    django.contrib.gis.db.models.fields.PointField(
                        geography=True, srid=4326
                    ),
                ),
                (
                    "dropoff_location",
                    django.contrib.gis.db.models.fields.PointField(
                        geography=True, srid=4326
                    ),
                ),
                ("pickup_address", models.TextField()),
                ("dropoff_address", models.TextField()),
                (
                    "estimated_distance",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                ("estimated_duration", models.IntegerField()),
                (
                    "estimated_price",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "final_distance",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("final_duration", models.IntegerField(blank=True, null=True)),
                (
                    "final_price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "discount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "rating",
                    models.IntegerField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ],
                    ),
                ),
                ("user_comment", models.TextField(blank=True)),
                (
                    "cancellation_reason",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("user_cancelled", "User Cancelled"),
                            ("driver_cancelled", "Driver Cancelled"),
                            ("no_drivers", "No Drivers Available"),
                            ("timeout", "Timeout"),
                            ("other", "Other"),
                        ],
                        max_length=50,
                    ),
                ),
                ("cancellation_comment", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("accepted_at", models.DateTimeField(blank=True, null=True)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("cancelled_at", models.DateTimeField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "driver",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="rides",
                        to="drivers.driver",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="rides",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Ride",
                "verbose_name_plural": "Rides",
                "db_table": "rides",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["status"], name="rides_status_376a74_idx"),
                    models.Index(
                        fields=["user", "status"], name="rides_user_id_d568ca_idx"
                    ),
                    models.Index(
                        fields=["driver", "status"], name="rides_driver__d736b9_idx"
                    ),
                    models.Index(
                        fields=["created_at"], name="rides_created_e430d2_idx"
                    ),
                    models.Index(
                        fields=["vehicle_type"], name="rides_vehicle_d04b30_idx"
                    ),
                ],
            },
        ),
    ]
