# Generated by Django 5.1.15 on 2026-04-13 14:46

import django.contrib.gis.db.models.fields
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("drivers", "0008_add_payment_reference"),
        ("payments", "0002_alter_payment_options_alter_promocode_options_and_more"),
        ("rides", "0002_ride_promo_code"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="ride",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Поїздка",
                "verbose_name_plural": "Поїздки",
            },
        ),
        migrations.AlterField(
            model_name="ride",
            name="accepted_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="Прийнято"),
        ),
        migrations.AlterField(
            model_name="ride",
            name="cancellation_comment",
            field=models.TextField(blank=True, verbose_name="Коментар скасування"),
        ),
        migrations.AlterField(
            model_name="ride",
            name="cancellation_reason",
            field=models.CharField(
                blank=True,
                choices=[
                    ("user_cancelled", "Скасовано пасажиром"),
                    ("driver_cancelled", "Скасовано водієм"),
                    ("no_drivers", "Немає водіїв"),
                    ("timeout", "Час очікування сплив"),
                    ("other", "Інше"),
                ],
                max_length=50,
                verbose_name="Причина скасування",
            ),
        ),
        migrations.AlterField(
            model_name="ride",
            name="cancelled_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="Скасовано"),
        ),
        migrations.AlterField(
            model_name="ride",
            name="completed_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="Завершено"),
        ),
        migrations.AlterField(
            model_name="ride",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, db_index=True, verbose_name="Створено"
            ),
        ),
        migrations.AlterField(
            model_name="ride",
            name="discount",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=10,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="Знижка",
            ),
        ),
        migrations.AlterField(
            model_name="ride",
            name="driver",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="rides",
                to="drivers.driver",
                verbose_name="Водій",
            ),
        ),
        migrations.AlterField(
            model_name="ride",
            name="dropoff_address",
            field=models.TextField(verbose_name="Адреса висадки"),
        ),
        migrations.AlterField(
            model_name="ride",
            name="dropoff_location",
            field=django.contrib.gis.db.models.fields.PointField(
                geography=True, srid=4326, verbose_name="Координати висадки"
            ),
        ),
        migrations.AlterField(
            model_name="ride",
            name="estimated_distance",
            field=models.DecimalField(
                decimal_places=2, max_digits=10, verbose_name="Очікувана відстань (км)"
            ),
        ),
        migrations.AlterField(
            model_name="ride",
            name="estimated_duration",
            field=models.IntegerField(verbose_name="Очікувана тривалість (хв)"),
        ),
        migrations.AlterField(
            model_name="ride",
            name="estimated_price",
            field=models.DecimalField(
                decimal_places=2, max_digits=10, verbose_name="Очікувана ціна"
            ),
        ),
        migrations.AlterField(
            model_name="ride",
            name="final_distance",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=10,
                null=True,
                verbose_name="Фактична відстань",
            ),
        ),
        migrations.AlterField(
            model_name="ride",
            name="final_duration",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="Фактична тривалість"
            ),
        ),
        migrations.AlterField(
            model_name="ride",
            name="final_price",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=10,
                null=True,
                verbose_name="Фактична ціна",
            ),
        ),
        migrations.AlterField(
            model_name="ride",
            name="pickup_address",
            field=models.TextField(verbose_name="Адреса посадки"),
        ),
        migrations.AlterField(
            model_name="ride",
            name="pickup_location",
            field=django.contrib.gis.db.models.fields.PointField(
                geography=True, srid=4326, verbose_name="Координати посадки"
            ),
        ),
        migrations.AlterField(
            model_name="ride",
            name="promo_code",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="rides",
                to="payments.promocode",
                verbose_name="Промокод",
            ),
        ),
        migrations.AlterField(
            model_name="ride",
            name="rating",
            field=models.IntegerField(
                blank=True,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(5),
                ],
                verbose_name="Оцінка",
            ),
        ),
        migrations.AlterField(
            model_name="ride",
            name="started_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="Розпочато"),
        ),
        migrations.AlterField(
            model_name="ride",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Очікує"),
                    ("accepted", "Прийнята"),
                    ("in_progress", "В дорозі"),
                    ("completed", "Завершена"),
                    ("cancelled", "Скасована"),
                ],
                db_index=True,
                default="pending",
                max_length=20,
                verbose_name="Статус",
            ),
        ),
        migrations.AlterField(
            model_name="ride",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="Оновлено"),
        ),
        migrations.AlterField(
            model_name="ride",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="rides",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Пасажир",
            ),
        ),
        migrations.AlterField(
            model_name="ride",
            name="user_comment",
            field=models.TextField(blank=True, verbose_name="Коментар пасажира"),
        ),
        migrations.AlterField(
            model_name="ride",
            name="vehicle_type",
            field=models.CharField(
                choices=[
                    ("economy", "Економ"),
                    ("comfort", "Комфорт"),
                    ("business", "Бізнес"),
                ],
                max_length=20,
                verbose_name="Тип авто",
            ),
        ),
    ]
