# Generated by Django 5.1.15 on 2026-04-13 22:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rides", "0003_alter_ride_options_alter_ride_accepted_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="ride",
            name="user_rating",
            field=models.PositiveIntegerField(
                blank=True,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(5),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="ride",
            name="user_comment",
            field=models.TextField(blank=True),
        ),
    ]
