# Generated by Django 5.1.15 on 2026-04-14 00:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rides", "0004_ride_user_rating_alter_ride_user_comment"),
    ]

    operations = [
        migrations.AddField(
            model_name="ride",
            name="driver_comment_for_passenger",
            field=models.TextField(
                blank=True, verbose_name="Коментар водія про пасажира"
            ),
        ),
        migrations.AddField(
            model_name="ride",
            name="driver_rating_for_passenger",
            field=models.IntegerField(
                blank=True,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(5),
                ],
                verbose_name="Оцінка пасажира водієм",
            ),
        ),
    ]
