# Generated by Django 5.1.15 on 2026-02-21 16:05

import django.contrib.gis.db.models.fields
import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Driver",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending Verification"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                            ("suspended", "Suspended"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "availability",
                    models.CharField(
                        choices=[
                            ("online", "Online"),
                            ("offline", "Offline"),
                            ("busy", "Busy"),
                        ],
                        db_index=True,
                        default="offline",
                        max_length=20,
                    ),
                ),
                (
                    "vehicle_type",
                    models.CharField(
                        choices=[
                            ("economy", "Economy"),
                            ("comfort", "Comfort"),
                            ("business", "Business"),
                        ],
                        default="economy",
                        max_length=20,
                    ),
                ),
                ("vehicle_make", models.CharField(max_length=100)),
                ("vehicle_model", models.CharField(max_length=100)),
                (
                    "vehicle_year",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(2000),
                            django.core.validators.MaxValueValidator(2030),
                        ]
                    ),
                ),
                ("vehicle_color", models.CharField(max_length=50)),
                ("vehicle_plate", models.CharField(max_length=20, unique=True)),
                ("license_number", models.CharField(max_length=50, unique=True)),
                ("license_expiry", models.DateField()),
                (
                    "current_location",
                    django.contrib.gis.db.models.fields.PointField(
                        blank=True,
                        geography=True,
                        help_text="Current GPS location",
                        null=True,
                        srid=4326,
                    ),
                ),
                ("location_updated_at", models.DateTimeField(blank=True, null=True)),
                (
                    "rating",
                    models.DecimalField(
                        decimal_places=2,
                        default=5.0,
                        max_digits=3,
                        validators=[
                            django.core.validators.MinValueValidator(1.0),
                            django.core.validators.MaxValueValidator(5.0),
                        ],
                    ),
                ),
                ("total_rides", models.IntegerField(default=0)),
                (
                    "total_earnings",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("rejection_reason", models.TextField(blank=True)),
                ("suspension_reason", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        help_text="User associated with this driver",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="driver_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Driver",
                "verbose_name_plural": "Drivers",
                "db_table": "drivers",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["status"], name="drivers_status_fa78f3_idx"),
                    models.Index(
                        fields=["availability"], name="drivers_availab_32b706_idx"
                    ),
                    models.Index(
                        fields=["vehicle_type"], name="drivers_vehicle_4e8406_idx"
                    ),
                    models.Index(fields=["rating"], name="drivers_rating_884ca4_idx"),
                ],
            },
        ),
    ]
