# Generated by Django 5.1.15 on 2026-04-05 16:52

import apps.drivers.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("drivers", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DriverDocument",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "doc_type",
                    models.CharField(
                        choices=[
                            ("driver_license", "Driver License"),
                            ("vehicle_registration", "Vehicle Registration"),
                            ("insurance_policy", "Insurance Policy"),
                            ("vehicle_photo", "Vehicle Photo"),
                        ],
                        help_text="Type of uploaded document",
                        max_length=50,
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        help_text="Uploaded document file (image or pdf)",
                        max_length=500,
                        upload_to=apps.drivers.models.driver_document_upload_to,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                        ],
                        default="pending",
                        help_text="Verification status of the document",
                        max_length=20,
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True, help_text="Reviewer notes or driver comments"
                    ),
                ),
                (
                    "expires_at",
                    models.DateField(
                        blank=True, help_text="Optional expiry date", null=True
                    ),
                ),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "driver",
                    models.ForeignKey(
                        help_text="Driver profile owner",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documents",
                        to="drivers.driver",
                    ),
                ),
                (
                    "reviewer",
                    models.ForeignKey(
                        blank=True,
                        help_text="Admin who reviewed the document",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reviewed_documents",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "driver_documents",
                "ordering": ["-uploaded_at"],
                "unique_together": {("driver", "doc_type")},
            },
        ),
    ]
