# Generated by Django 5.1.15 on 2026-04-07 08:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("drivers", "0002_driverdocument"),
    ]

    operations = [
        migrations.AlterField(
            model_name="driver",
            name="license_expiry",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="driver",
            name="license_number",
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="driver",
            name="vehicle_color",
            field=models.CharField(blank=True, default="", max_length=50),
        ),
        migrations.AlterField(
            model_name="driver",
            name="vehicle_make",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.AlterField(
            model_name="driver",
            name="vehicle_model",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.AlterField(
            model_name="driver",
            name="vehicle_plate",
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="driver",
            name="vehicle_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("economy", "Economy"),
                    ("comfort", "Comfort"),
                    ("business", "Business"),
                ],
                default="economy",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="driver",
            name="vehicle_year",
            field=models.IntegerField(
                blank=True,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(2000),
                    django.core.validators.MaxValueValidator(2030),
                ],
            ),
        ),
    ]
