# Generated by Django 5.1.15 on 2026-04-08 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("drivers", "0003_alter_driver_license_expiry_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="driver",
            name="first_name",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.AddField(
            model_name="driver",
            name="last_name",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.AlterField(
            model_name="driverdocument",
            name="doc_type",
            field=models.CharField(
                choices=[
                    ("driver_license", "Driver License"),
                    ("vehicle_registration", "Vehicle Registration"),
                    ("insurance_policy", "Insurance Policy"),
                    ("vehicle_photo", "Vehicle Photo"),
                    ("vehicle_photo_2", "Vehicle Photo 2"),
                    ("vehicle_photo_3", "Vehicle Photo 3"),
                ],
                help_text="Type of uploaded document",
                max_length=50,
            ),
        ),
    ]
