# Generated by Django 5.1.15 on 2026-04-10 14:31

import apps.drivers.models
import django.contrib.gis.db.models.fields
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("drivers", "0004_driver_first_name_driver_last_name_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="driver",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Водій",
                "verbose_name_plural": "Водії",
            },
        ),
        migrations.AlterModelOptions(
            name="driverdocument",
            options={
                "ordering": ["-uploaded_at"],
                "verbose_name": "Документ водія",
                "verbose_name_plural": "Документи водія",
            },
        ),
        migrations.AddField(
            model_name="driver",
            name="card_earnings",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=10,
                verbose_name="Заробіток карткою",
            ),
        ),
        migrations.AddField(
            model_name="driver",
            name="cash_earnings",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=10,
                verbose_name="Заробіток готівкою",
            ),
        ),
        migrations.AddField(
            model_name="driver",
            name="pending_card_withdrawal",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=10,
                verbose_name="Очікує виведення (картка)",
            ),
        ),
        migrations.AlterField(
            model_name="driver",
            name="availability",
            field=models.CharField(
                choices=[
                    ("online", "Online"),
                    ("offline", "Offline"),
                    ("busy", "Зайнятий"),
                ],
                db_index=True,
                default="offline",
                max_length=20,
                verbose_name="Доступність",
            ),
        ),
        migrations.AlterField(
            model_name="driver",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Створено"),
        ),
        migrations.AlterField(
            model_name="driver",
            name="current_location",
            field=django.contrib.gis.db.models.fields.PointField(
                blank=True,
                geography=True,
                null=True,
                srid=4326,
                verbose_name="Поточне місцезнаходження",
            ),
        ),
        migrations.AlterField(
            model_name="driver",
            name="first_name",
            field=models.CharField(
                blank=True, default="", max_length=100, verbose_name="Ім'я"
            ),
        ),
        migrations.AlterField(
            model_name="driver",
            name="last_name",
            field=models.CharField(
                blank=True, default="", max_length=100, verbose_name="Прізвище"
            ),
        ),
        migrations.AlterField(
            model_name="driver",
            name="license_expiry",
            field=models.DateField(blank=True, null=True, verbose_name="Дійсне до"),
        ),
        migrations.AlterField(
            model_name="driver",
            name="license_number",
            field=models.CharField(
                blank=True,
                max_length=50,
                null=True,
                unique=True,
                verbose_name="Номер посвідчення",
            ),
        ),
        migrations.AlterField(
            model_name="driver",
            name="location_updated_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Місцезнаходження оновлено"
            ),
        ),
        migrations.AlterField(
            model_name="driver",
            name="rating",
            field=models.DecimalField(
                decimal_places=2,
                default=5.0,
                max_digits=3,
                validators=[
                    django.core.validators.MinValueValidator(1.0),
                    django.core.validators.MaxValueValidator(5.0),
                ],
                verbose_name="Рейтинг",
            ),
        ),
        migrations.AlterField(
            model_name="driver",
            name="rejection_reason",
            field=models.TextField(blank=True, verbose_name="Причина відмови"),
        ),
        migrations.AlterField(
            model_name="driver",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Очікує перевірки"),
                    ("approved", "Схвалено"),
                    ("rejected", "Відхилено"),
                    ("suspended", "Заблоковано"),
                ],
                db_index=True,
                default="pending",
                max_length=20,
                verbose_name="Статус",
            ),
        ),
        migrations.AlterField(
            model_name="driver",
            name="suspension_reason",
            field=models.TextField(blank=True, verbose_name="Причина блокування"),
        ),
        migrations.AlterField(
            model_name="driver",
            name="total_earnings",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=10,
                verbose_name="Загальний заробіток",
            ),
        ),
        migrations.AlterField(
            model_name="driver",
            name="total_rides",
            field=models.IntegerField(default=0, verbose_name="Всього поїздок"),
        ),
        migrations.AlterField(
            model_name="driver",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="Оновлено"),
        ),
        migrations.AlterField(
            model_name="driver",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="driver_profile",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Користувач",
            ),
        ),
        migrations.AlterField(
            model_name="driver",
            name="vehicle_color",
            field=models.CharField(
                blank=True, default="", max_length=50, verbose_name="Колір"
            ),
        ),
        migrations.AlterField(
            model_name="driver",
            name="vehicle_make",
            field=models.CharField(
                blank=True, default="", max_length=100, verbose_name="Марка"
            ),
        ),
        migrations.AlterField(
            model_name="driver",
            name="vehicle_model",
            field=models.CharField(
                blank=True, default="", max_length=100, verbose_name="Модель"
            ),
        ),
        migrations.AlterField(
            model_name="driver",
            name="vehicle_plate",
            field=models.CharField(
                blank=True,
                max_length=20,
                null=True,
                unique=True,
                verbose_name="Номерний знак",
            ),
        ),
        migrations.AlterField(
            model_name="driver",
            name="vehicle_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("economy", "Економ"),
                    ("comfort", "Комфорт"),
                    ("business", "Бізнес"),
                ],
                default="economy",
                max_length=20,
                verbose_name="Тип авто",
            ),
        ),
        migrations.AlterField(
            model_name="driver",
            name="vehicle_year",
            field=models.IntegerField(
                blank=True,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(2000),
                    django.core.validators.MaxValueValidator(2030),
                ],
                verbose_name="Рік випуску",
            ),
        ),
        migrations.AlterField(
            model_name="driverdocument",
            name="doc_type",
            field=models.CharField(
                choices=[
                    ("driver_license", "Водійське посвідчення"),
                    ("vehicle_registration", "Техпаспорт"),
                    ("insurance_policy", "Страховий поліс"),
                    ("vehicle_photo", "Фото авто 1"),
                    ("vehicle_photo_2", "Фото авто 2"),
                    ("vehicle_photo_3", "Фото авто 3"),
                ],
                max_length=50,
                verbose_name="Тип документа",
            ),
        ),
        migrations.AlterField(
            model_name="driverdocument",
            name="expires_at",
            field=models.DateField(blank=True, null=True, verbose_name="Дійсне до"),
        ),
        migrations.AlterField(
            model_name="driverdocument",
            name="file",
            field=models.FileField(
                max_length=500,
                upload_to=apps.drivers.models.driver_document_upload_to,
                verbose_name="Файл",
            ),
        ),
        migrations.AlterField(
            model_name="driverdocument",
            name="notes",
            field=models.TextField(blank=True, verbose_name="Нотатки"),
        ),
        migrations.AlterField(
            model_name="driverdocument",
            name="reviewed_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Перевірено"
            ),
        ),
        migrations.AlterField(
            model_name="driverdocument",
            name="reviewer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="reviewed_documents",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Перевіряв",
            ),
        ),
        migrations.AlterField(
            model_name="driverdocument",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Очікує перевірки"),
                    ("approved", "Схвалено"),
                    ("rejected", "Відхилено"),
                ],
                default="pending",
                max_length=20,
                verbose_name="Статус",
            ),
        ),
        migrations.AlterField(
            model_name="driverdocument",
            name="uploaded_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Завантажено"),
        ),
    ]
