# Generated by Django 5.1.15 on 2026-04-10 14:33

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("drivers", "0005_alter_driver_options_alter_driverdocument_options_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="WithdrawalRequest",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0.01)],
                        verbose_name="Сума виведення",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Очікує розгляду"),
                            ("approved", "Схвалено"),
                            ("rejected", "Відхилено"),
                            ("completed", "Виплачено"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=20,
                        verbose_name="Статус",
                    ),
                ),
                (
                    "admin_comment",
                    models.TextField(
                        blank=True, verbose_name="Коментар адміністратора"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Створено"),
                ),
                (
                    "resolved_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Оброблено"
                    ),
                ),
                (
                    "driver",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="withdrawal_requests",
                        to="drivers.driver",
                        verbose_name="Водій",
                    ),
                ),
            ],
            options={
                "verbose_name": "Запит на виведення",
                "verbose_name_plural": "Запити на виведення",
                "db_table": "withdrawal_requests",
                "ordering": ["-created_at"],
            },
        ),
    ]
