# Generated by Django 5.1.15 on 2026-04-11 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("drivers", "0006_withdrawalrequest"),
    ]

    operations = [
        migrations.AddField(
            model_name="driver",
            name="payout_card_number",
            field=models.CharField(
                blank=True,
                default="",
                max_length=19,
                verbose_name="Номер картки для виплати",
            ),
        ),
    ]
