# Generated by Django 5.1.15 on 2026-04-11 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("drivers", "0007_add_payout_card_number"),
    ]

    operations = [
        migrations.AddField(
            model_name="withdrawalrequest",
            name="payment_reference",
            field=models.CharField(
                blank=True,
                default="",
                max_length=200,
                verbose_name="Номер транзакції / квитанції",
            ),
        ),
    ]
