# Generated by Django 5.1.15 on 2026-04-13 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("drivers", "0008_add_payment_reference"),
    ]

    operations = [
        migrations.AddField(
            model_name="driver",
            name="heading",
            field=models.FloatField(
                blank=True, null=True, verbose_name="Напрямок руху (градуси)"
            ),
        ),
        migrations.AddField(
            model_name="driver",
            name="speed",
            field=models.FloatField(
                blank=True, null=True, verbose_name="Швидкість (км/год)"
            ),
        ),
    ]
