# Generated by Django 5.1.15 on 2026-04-13 14:46

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0001_initial"),
        ("rides", "0002_ride_promo_code"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="payment",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Платіж",
                "verbose_name_plural": "Платежі",
            },
        ),
        migrations.AlterModelOptions(
            name="promocode",
            options={"verbose_name": "Промокод", "verbose_name_plural": "Промокоди"},
        ),
        migrations.AlterModelOptions(
            name="refund",
            options={"verbose_name": "Повернення", "verbose_name_plural": "Повернення"},
        ),
        migrations.AlterField(
            model_name="payment",
            name="amount",
            field=models.DecimalField(
                decimal_places=2,
                max_digits=10,
                validators=[django.core.validators.MinValueValidator(Decimal("0.01"))],
                verbose_name="Сума",
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, db_index=True, verbose_name="Створено"
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="currency",
            field=models.CharField(default="UAH", max_length=3, verbose_name="Валюта"),
        ),
        migrations.AlterField(
            model_name="payment",
            name="description",
            field=models.TextField(blank=True, verbose_name="Опис"),
        ),
        migrations.AlterField(
            model_name="payment",
            name="error_message",
            field=models.TextField(blank=True, verbose_name="Повідомлення про помилку"),
        ),
        migrations.AlterField(
            model_name="payment",
            name="failed_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="Помилка о"),
        ),
        migrations.AlterField(
            model_name="payment",
            name="payment_method",
            field=models.CharField(
                choices=[
                    ("card", "Картка"),
                    ("google_pay", "Google Pay"),
                    ("apple_pay", "Apple Pay"),
                    ("cash", "Готівка"),
                ],
                max_length=20,
                verbose_name="Спосіб оплати",
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="processed_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="Оброблено"),
        ),
        migrations.AlterField(
            model_name="payment",
            name="provider",
            field=models.CharField(
                choices=[("liqpay", "LiqPay"), ("fondy", "Fondy"), ("cash", "Готівка")],
                max_length=20,
                verbose_name="Провайдер",
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="provider_data",
            field=models.JSONField(
                blank=True, default=dict, verbose_name="Дані провайдера"
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="provider_transaction_id",
            field=models.CharField(
                blank=True,
                db_index=True,
                max_length=255,
                null=True,
                unique=True,
                verbose_name="ID транзакції",
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="refunded_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Повернуто о"
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="ride",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="payments",
                to="rides.ride",
                verbose_name="Поїздка",
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Очікує"),
                    ("processing", "Обробляється"),
                    ("success", "Успішно"),
                    ("failed", "Помилка"),
                    ("refunded", "Повернуто"),
                    ("cancelled", "Скасовано"),
                    ("expired", "Строк сплив"),
                    ("partial_refund", "Часткове повернення"),
                ],
                db_index=True,
                default="pending",
                max_length=20,
                verbose_name="Статус",
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="Оновлено"),
        ),
        migrations.AlterField(
            model_name="payment",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="payments",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Користувач",
            ),
        ),
        migrations.AlterField(
            model_name="promocode",
            name="code",
            field=models.CharField(
                db_index=True, max_length=50, unique=True, verbose_name="Код"
            ),
        ),
        migrations.AlterField(
            model_name="promocode",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Створено"),
        ),
        migrations.AlterField(
            model_name="promocode",
            name="discount_amount",
            field=models.DecimalField(
                decimal_places=2, default=0, max_digits=10, verbose_name="Сума знижки"
            ),
        ),
        migrations.AlterField(
            model_name="promocode",
            name="discount_percent",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=5,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(100),
                ],
                verbose_name="Відсоток знижки (%)",
            ),
        ),
        migrations.AlterField(
            model_name="promocode",
            name="discount_type",
            field=models.CharField(
                choices=[("percentage", "Відсоткова"), ("fixed", "Фіксова сума")],
                default="percentage",
                max_length=20,
                verbose_name="Тип знижки",
            ),
        ),
        migrations.AlterField(
            model_name="promocode",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="Активний"),
        ),
        migrations.AlterField(
            model_name="promocode",
            name="max_discount",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=10,
                null=True,
                verbose_name="Макс знижка",
            ),
        ),
        migrations.AlterField(
            model_name="promocode",
            name="min_ride_price",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=10,
                verbose_name="Мін сума поїздки",
            ),
        ),
        migrations.AlterField(
            model_name="promocode",
            name="usage_count",
            field=models.IntegerField(default=0, verbose_name="Кількість використань"),
        ),
        migrations.AlterField(
            model_name="promocode",
            name="usage_limit",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="Ліміт використань"
            ),
        ),
        migrations.AlterField(
            model_name="promocode",
            name="valid_from",
            field=models.DateTimeField(
                default=django.utils.timezone.now, verbose_name="Дійсний з"
            ),
        ),
        migrations.AlterField(
            model_name="promocode",
            name="valid_until",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Дійсний до"
            ),
        ),
        migrations.AlterField(
            model_name="refund",
            name="amount",
            field=models.DecimalField(
                decimal_places=2, max_digits=10, verbose_name="Сума"
            ),
        ),
        migrations.AlterField(
            model_name="refund",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Створено"),
        ),
        migrations.AlterField(
            model_name="refund",
            name="payment",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="refunds",
                to="payments.payment",
                verbose_name="Платіж",
            ),
        ),
        migrations.AlterField(
            model_name="refund",
            name="processed_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="Оброблено"),
        ),
        migrations.AlterField(
            model_name="refund",
            name="provider_refund_id",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="ID повернення"
            ),
        ),
        migrations.AlterField(
            model_name="refund",
            name="reason",
            field=models.TextField(verbose_name="Причина"),
        ),
        migrations.AlterField(
            model_name="refund",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Очікує"),
                    ("processing", "Обробляється"),
                    ("success", "Успішно"),
                    ("failed", "Помилка"),
                ],
                default="pending",
                max_length=20,
                verbose_name="Статус",
            ),
        ),
    ]
